[package]
name = "WebPforming"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.6", default-features = false, features = ["webp", "png", "jpeg", "gif", "bmp"] }
rayon = "1.10.0"

[profile.release]
lto = true
strip = true
